version = 1
SPDX-PackageName = "SS14 Harmony"
SPDX-PackageSupplier = "Kelderan <66748890+KeldWolf@users.noreply.github.com>"
SPDX-PackageDownloadLocation = "https://github.com/ss14-harmony/ss14-harmony"

[[annotations]]
path = ["Resources/Audio/**", "Resources/Textures/**"]
precedence = "aggregate"
SPDX-FileCopyrightText = "None"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = ["*", "**.json"]
precedence = "aggregate"
SPDX-FileCopyrightText = "None"
SPDX-License-Identifier = "MIT"
