name: "Labels: PR"

on:
- pull_request_target

jobs:
  labeler:
    if: github.actor != 'PJBot'
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    # Harmony start
    - name: Get Current Labels
      id: get_current_labels
      uses: snnaplab/get-labels-action@v1.0.1
      continue-on-error: true
    # Harmony end
    - uses: actions/labeler@v5
      # Harmony start
      if: ${{ (env.LABELS == '') || (! contains(env.LABELS, 'Maintenance')) }}
      with:
        sync-labels: true
      # Harmony end
