name: Test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: unbuntu-latest

    steps:
    - uses: actions/checkout@v4.2.2
    - name: Test
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo "$GITHUB_TOKEN"
