# SPDX-FileCopyrightText: 2025 Aiden <28298836+Aidenkrz@users.noreply.github.com>
# SPDX-FileCopyrightText: 2025 Aidenkrz <28298836+Aidenkrz@users.noreply.github.com>
# SPDX-FileCopyrightText: 2025 youtissoum <51883137+youtissoum@users.noreply.github.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

# A lot of this is taken from Goob

name: Update REUSE headers

on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

jobs:
  update_headers:
    name: Update REUSE headers
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.head_ref }}
          fetch-depth: 0
          token: ${{ secrets.BOT_TOKEN }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install the REUSE tool
        uses: BSFishy/pip-action@v1
        with:
          packages: reuse

      - name: Get changed files
        id: changed-files
        env:
          GH_TOKEN: ${{ secrets.BOT_TOKEN }}
          GH_REPO: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          set -e # Exit script on first error

          echo "Fetching files for PR #${PR_NUMBER} in repo ${GH_REPO}"

          PR_FILES_JSON=$(curl -s -f \
            "https://api.github.com/repos/${GH_REPO}/pulls/${PR_NUMBER}/files")

          if [ $? -ne 0 ]; then
            echo "Error fetching PR files from GitHub API."
            exit 1
          fi

          if ! echo "$PR_FILES_JSON" | jq -e . > /dev/null; then
             echo "Warning: Received empty or invalid JSON from GitHub API for PR files."
             PR_FILES="" # Set PR_FILES to empty to avoid errors below
          else
             PR_FILES=$(echo "$PR_FILES_JSON" | jq -r '.[] | select(.filename != null) | "\(.filename)"')
          fi

          echo "Files: $PR_FILES"

          echo "PR_FILES_LIST<<EOF" >> $GITHUB_ENV
          echo "$PR_FILES" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Generate updated headers
        run: |
          Tools/update_reuse_headers.py $(echo "${{ env.PR_FILES_LIST }}" | tr '\n' ' ')
        working-directory: ${{ github.workspace }}

      - name: Sanity check the output
        run: |
          reuse lint-file $(echo "${{ env.PR_FILES_LIST }}" | tr '\n' ' ')
        working-directory: ${{ github.workspace }}

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Automatically update REUSE headers"
          commit_user_name: ${{ vars.BOT_USER }}
          commit_user_email: ${{ vars.BOT_EMAIL }}
          commit_author: ${{ VARS.BOT_USER }} <${{ vars.BOT_EMAIL }}>
          skip_dirty_check: false
          skip_fetch: true
